# PROJECT:EXPLORING EBAY CAR SALES DATA
 #### INTRODUCTION 
  In this project, I'll be exploring ebay car sales data.I will be making use of a dataset of used cars from eBay Kleinanzeigen which is a classified section of the GermaneBay website.

In [226]:
import pandas as pd
import numpy as np

autos = pd.read_csv('autos.csv' )

In [227]:
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [228]:
print(autos.info())
print(autos.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB
None
           dateCrawled                                               name  \
0  2016-03-26 17:47:46                   Peugeot_807_160_NAVTECH_ON_BOARD
1  2016-04-04 13:38:56         BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik
2  2016-03-26 18:57:24                         Volkswagen_Golf_1.6_United
3  2016-03-12 16:58:10  Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...
4  2016-04-01 14:38:50  Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...

   seller offerType   price   abtest vehicleType  yearOfRegistration  \
0  privat   Angebot  $5,000  control         bus                2004
1  privat   Angebot  $8,500  control   limousine                1997
2  privat   Angebot  $8,990     test   limousine                2009
3  privat   Angebot  $4,350  control  kleinwagen                2007
4  privat   Angebot  $1,350     test       kombi                2003

     gearbox  powerPS   model   odometer  monthOfRegistration fuelType  \
0    manuell      158  andere  150,000km                    3      lpg
1  automatik      286     7er  150,000km                    6   benzin
2    manuell      102    golf   70,000km                    7   benzin
3  automatik       71  fortwo   70,000km                    6   benzin
4    manuell        0   focus  150,000km                    7   benzin

        brand notRepairedDamage          dateCreated  nrOfPictures  \
0     peugeot              nein  2016-03-26 00:00:00             0
1         bmw              nein  2016-04-04 00:00:00             0
2  volkswagen              nein  2016-03-26 00:00:00             0
3       smart              nein  2016-03-12 00:00:00             0
4        ford              nein  2016-04-01 00:00:00             0

   postalCode             lastSeen
0       79588  2016-04-06 06:45:54
1       71034  2016-04-06 14:45:08
2       35394  2016-04-06 20:15:37
3       33729  2016-03-15 03:16:28
4       39218  2016-04-01 14:38:50

### OBERVATION FROM THE DATASET
This dataset has a total of 50000 rows and 20 columns which consists of both strings and integers. The dataset also has some rows with null objects which means that those rows have invalid inputs.

In [229]:
autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [230]:
autos.columns = ['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'power_ps', 'model',
       'odometer', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
       'last_seen']
autos.head()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

I made some changes in the 'autos.column arrays' above by replacing strings written in uppercase to '_'. This is best known as changing from camelcase to snakecase. I changed from camelcase to snakecase because snakecase is preferable when working with python.

In [231]:
autos.describe(include='all')

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-03-10 15:36:24,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

#### OBSERVATIONS FROM DESCRIPTIVE STATISTICS:
1. Most columns have most of their values to be the same, especially the 'seller' and 'offer_type' columns.
2. The 'nr_of_pictures' seems to have a lot of 0.0 values in its statistics. It needs to be investigated more.
3. The 'price' and 'odometer' columns has numeric data stored as text and this needs to be cleaned.

In [232]:
autos['nr_of_pictures'].value_counts()

0    50000
Name: nr_of_pictures, dtype: int64

The 'nr_of_pictures' column has all its values to be 0 so we will have to drop this column. We will also drop the 'seller'and 'offer_type' columns because they each have mostly the same values.

In [233]:
autos.drop(['nr_of_pictures', 'seller', 'offer_type'], axis=1)

,date_crawled,name,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,45897,2016-04-06 21:18:48

In [234]:
autos["price"] = autos["price"].str.replace('$', '').str.replace(',', '') .astype(int)
                           
autos['price'].head()

0    5000
1    8500
2    8990
3    4350
4    1350
Name: price, dtype: int64

In [235]:
autos['odometer'] = autos['odometer'].str.replace('km','').str.replace(',', '').astype(int)
autos.rename({'odometer': 'odometer_km'}, axis = 1, inplace=True)
autos['odometer_km'].head()

0    150000
1    150000
2     70000
3     70000
4    150000
Name: odometer_km, dtype: int64

In [236]:
autos['odometer_km'].value_counts()

150000    32424
125000     5170
100000     2169
90000      1757
80000      1436
70000      1230
60000      1164
50000      1027
5000        967
40000       819
30000       789
20000       784
10000       264
Name: odometer_km, dtype: int64

From the count above, you can observe that cars with the highest number of milleage has the highest number of counts. This means that there are more cars with high milleage than cars with low milleage.

In [237]:
print(autos['price'].unique().shape)
print(autos['price'].describe())
print(autos['price'].value_counts().head(20))

(2357,)
count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price, dtype: float64
0       1421
500      781
1500     734
2500     643
1000     639
1200     639
600      531
800      498
3500     498
2000     460
999      434
750      433
900      420
650      419
850      410
700      395
4500     394
300      384
2200     382
950      379
Name: price, dtype: int64

There are 1421 car listings with a price of 0 which is lie 2% 0f the total number of cars. we can remove these rows. We can also see that the highest price is one hendred milloin which seems very high so let's look at the highest and lowest prices further.

In [238]:
autos['price'].value_counts().sort_index(ascending=False).head(20)

99999999    1
27322222    1
12345678    3
11111111    2
10000000    1
3890000     1
1300000     1
1234566     1
999999      2
999990      1
350000      1
345000      1
299000      1
295000      1
265000      1
259000      1
250000      1
220000      1
198000      1
197000      1
Name: price, dtype: int64

There are a number of listings with ridiculously high prices of around and above one million including 14. We will remove these rows since the other prices seem to increase normally upto 350000 before going up very high to prices that are less realistic.

In [239]:
autos['price'].value_counts().sort_index(ascending=True).head(20)

0     1421
1      156
2        3
3        1
5        2
8        1
9        1
10       7
11       2
12       3
13       2
14       1
15       2
17       3
18       1
20       4
25       5
29       1
30       7
35       1
Name: price, dtype: int64

There are a number of listings with prices below 30 including around 1500 for 0. We will have to remove rows with such prices but we will leave rows from 1 above considering that eBay is an auction site and biddings might start from 1.

In [240]:
autos = autos[autos['price'].between(1,351000)]
autos['price'].describe()

count     48565.000000
mean       5888.935591
std        9059.854754
min           1.000000
25%        1200.000000
50%        3000.000000
75%        7490.000000
max      350000.000000
Name: price, dtype: float64

In [241]:
autos['date_crawled'].str[:10].value_counts(normalize=True, dropna=False).sort_index()

2016-03-05    0.025327
2016-03-06    0.014043
2016-03-07    0.036014
2016-03-08    0.033296
2016-03-09    0.033090
2016-03-10    0.032184
2016-03-11    0.032575
2016-03-12    0.036920
2016-03-13    0.015670
2016-03-14    0.036549
2016-03-15    0.034284
2016-03-16    0.029610
2016-03-17    0.031628
2016-03-18    0.012911
2016-03-19    0.034778
2016-03-20    0.037887
2016-03-21    0.037373
2016-03-22    0.032987
2016-03-23    0.032225
2016-03-24    0.029342
2016-03-25    0.031607
2016-03-26    0.032204
2016-03-27    0.031092
2016-03-28    0.034860
2016-03-29    0.034099
2016-03-30    0.033687
2016-03-31    0.031834
2016-04-01    0.033687
2016-04-02    0.035478
2016-04-03    0.038608
2016-04-04    0.036487
2016-04-05    0.013096
2016-04-06    0.003171
2016-04-07    0.001400
Name: date_crawled, dtype: float64

The distribution of listings crawled on each day is uniform for rouhgly one month which is between 5th March to 7th April 2016.

In [242]:
autos['ad_created'].str[:10].value_counts(normalize=True, dropna=False).sort_index()

2015-06-11    0.000021
2015-08-10    0.000021
2015-09-09    0.000021
2015-11-10    0.000021
2015-12-05    0.000021
2015-12-30    0.000021
2016-01-03    0.000021
2016-01-07    0.000021
2016-01-10    0.000041
2016-01-13    0.000021
2016-01-14    0.000021
2016-01-16    0.000021
2016-01-22    0.000021
2016-01-27    0.000062
2016-01-29    0.000021
2016-02-01    0.000021
2016-02-02    0.000041
2016-02-05    0.000041
2016-02-07    0.000021
2016-02-08    0.000021
2016-02-09    0.000021
2016-02-11    0.000021
2016-02-12    0.000041
2016-02-14    0.000041
2016-02-16    0.000021
2016-02-17    0.000021
2016-02-18    0.000041
2016-02-19    0.000062
2016-02-20    0.000041
2016-02-21    0.000062
                ...
2016-03-09    0.033151
2016-03-10    0.031895
2016-03-11    0.032904
2016-03-12    0.036755
2016-03-13    0.017008
2016-03-14    0.035190
2016-03-15    0.034016
2016-03-16    0.030125
2016-03-17    0.031278
2016-03-18    0.013590
2016-03-19    0.033687
2016-03-20    0.037949
2016-03-21    0.037579
2016-03-22    0.032801
2016-03-23    0.032060
2016-03-24    0.029280
2016-03-25    0.031751
2016-03-26    0.032266
2016-03-27    0.030989
2016-03-28    0.034984
2016-03-29    0.034037
2016-03-30    0.033501
2016-03-31    0.031875
2016-04-01    0.033687
2016-04-02    0.035149
2016-04-03    0.038855
2016-04-04    0.036858
2016-04-05    0.011819
2016-04-06    0.003253
2016-04-07    0.001256
Name: ad_created, Length: 76, dtype: float64

There are a variety of ad created dates in the listings. Most which occur within the range 1-2 months of the listing dates although some of the dates are quite old with the oldest being around 9months.

In [243]:
autos['last_seen'].str[:10].value_counts(normalize=True, dropna=False).sort_index()

2016-03-05    0.001071
2016-03-06    0.004324
2016-03-07    0.005395
2016-03-08    0.007413
2016-03-09    0.009595
2016-03-10    0.010666
2016-03-11    0.012375
2016-03-12    0.023783
2016-03-13    0.008895
2016-03-14    0.012602
2016-03-15    0.015876
2016-03-16    0.016452
2016-03-17    0.028086
2016-03-18    0.007351
2016-03-19    0.015834
2016-03-20    0.020653
2016-03-21    0.020632
2016-03-22    0.021373
2016-03-23    0.018532
2016-03-24    0.019767
2016-03-25    0.019211
2016-03-26    0.016802
2016-03-27    0.015649
2016-03-28    0.020859
2016-03-29    0.022341
2016-03-30    0.024771
2016-03-31    0.023783
2016-04-01    0.022794
2016-04-02    0.024915
2016-04-03    0.025203
2016-04-04    0.024483
2016-04-05    0.124761
2016-04-06    0.221806
2016-04-07    0.131947
Name: last_seen, dtype: float64

This enables us to know when last a listing was seen which indicates whent the listing was removed or presumably when a was sold. 
from the information above, the 'last seen' values from 5th-7th April is very high compared to the other values.

In [244]:
autos['registration_year'].describe()

count    48565.000000
mean      2004.755421
std         88.643887
min       1000.000000
25%       1999.000000
50%       2004.000000
75%       2008.000000
max       9999.000000
Name: registration_year, dtype: float64

The regitration year of the car indicates the age of the car but the minimum and maximum values from the column description is odd. It has min of 1000 which is years befor cars were invented and max value of 9999 which is years into the future.

In [245]:
(~autos['registration_year'].between(1900,2016)).sum() / autos.shape[0]

0.038793369710697

I picked a highest value of 2016 and lowest value of 1900 for registration year to be my range for valid data and calculated the percentage of my total data that has invalid data. And from the result above, the invalid data is of a very small percentage, therefore my decision is to remove this invalid data from the rgistration year column.

In [246]:
autos = autos[autos['registration_year'].between(1900,2016)]
autos['registration_year'].value_counts(normalize=True).head(10)

2000    0.067608
2005    0.062895
1999    0.062060
2004    0.057904
2003    0.057818
2006    0.057197
2001    0.056468
2002    0.053255
1998    0.050620
2007    0.048778
Name: registration_year, dtype: float64

Most of the vehicles were first registered 20years ago

In [247]:
brand_count = autos['brand'].value_counts(normalize = True)

Volkswagen is the most popular brand by listing and there are a lot of other brands with insignificant percentage of listings. So I have decided to aggregate by brands with listings more than five percent of the total listing.

In [248]:
common_brands = brand_count[brand_count > 0.05].index
print(common_brands)

Index(['volkswagen', 'bmw', 'opel', 'mercedes_benz', 'audi', 'ford'], dtype='object')

In [249]:
brand_mean_prices = {}

for brand in common_brands:
    only_brand = autos[autos['brand'] == brand]
    mean_price = only_brand['price'].mean()
    brand_mean_prices[brand] = int(mean_price)
brand_mean_prices

{'audi': 9336,
 'bmw': 8332,
 'ford': 3749,
 'mercedes_benz': 8628,
 'opel': 2975,
 'volkswagen': 5402}

Of the top 6 car brands, audi, mercedes benz and bmw are the most expensive respectively while ford and opel are less expensive. Volkswagen is in the middle, this could also explain why it is the most popular car brand because it is not too expensive and not too cheap.

In [250]:
brand_mean_mileage = {}

for brand in common_brands:
    only_brand = autos[autos['brand'] == brand]
    mean_mileage = only_brand['odometer_km'].mean()
    brand_mean_mileage[brand] = int(mean_mileage)
    
mean_mileage = pd.Series(brand_mean_mileage).sort_values(ascending=False)
mean_price = pd.Series(brand_mean_prices).sort_values(ascending=False)

In [251]:
brand_info = pd.DataFrame(mean_mileage,columns = ['mean_mileage'])
brand_info

               mean_mileage
bmw                  132572
mercedes_benz        130788
opel                 129310
audi                 129157
volkswagen           128707
ford                 124266

In [252]:
brand_info['mean_price'] = mean_price
brand_info

               mean_mileage  mean_price
bmw                  132572        8332
mercedes_benz        130788        8628
opel                 129310        2975
audi                 129157        9336
volkswagen           128707        5402
ford                 124266        3749

The range of car mileages does not vary as much as the prices do by brand, instead all falling within 10% for the top brands. There is a slight trend to the more expensive vehicles having higher mileage, with the less expensive vehicles having lower mileage.